### PR TITLE
save card fix

### PR DESCRIPTION
**Pull request by mstein-ck**
PSUP-4454
Error saving card should not cause transaction to fail
Increment version
Add to changelog

### CODE REVIEW

**Comment by mstein-ck** [comment]
@dehrentrei-ck can you review

**Comment by dlehren** [comment]
> @dehrentrei-ck can you review

This looks good, please test simulating the issue to confirm that this helps.

**Review by ymwymw — APPROVED** [review]

**Comment by ymwymw** [comment]
@mstein-ck Sonar needs to pass in order to merge

**Comment by mstein-ck** [comment]
> 
> 
> @mstein-ck Sonar needs to pass in order to merge

@ymwymw I don't feel comfortable refactoring this code and I think this change needs to be released.
Can Sonarcloud be ignored for this PR?

**Comment by ymwymw** [comment]
ok

**Pull request merged**
