### PR TITLE
Checkout page applyfocus and add link

### PR DESCRIPTION
**Pull request by pritesh-lr**

### CODE REVIEW

**Review by mstein-ck — DISMISSED** [review]

**Comment by mstein-ck** [comment]
I don't see any un-minified changes?

**Comment by pritesh-lr** [comment]
Hello @mstein-ck 
This minified file differs only in whitespace compared to the original; there are no other changes. This task relates to adding a red border for displaying validation messages, which has already been completed.

image
image

**Comment by mstein-ck** [comment]
Can this PR be closed?

**Comment by pritesh-lr** [comment]
Hello @mstein-ck 
Yes Please Close this PR.

**Review by mstein-ck — APPROVED** [review]

**Pull request merged**
